# Project Milestone 2
* Data Preparation: DSC 540-T302 
* Mallory Young
* Student #21356619

In [1]:
#importing libraries I might need for this data transformation and/or cleansing
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#use the pandas pd.read_csv function to load the data from the downloaded csv file
Holywd_gross_df = pd.read_csv('Highest Holywood Grossing Movies.csv')
#display the first 5 rows of the dataframe
Holywd_gross_df.head()

,Unnamed: 0,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License
0,0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
1,1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000,1941066100,2799439100,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022,20th Century Studios,December 14 2022 (EMEA APAC),134100226,684075767,1636174514,2320250281,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
3,3,Titanic,A seventeen-year-old aristocrat falls in love ...,1997,Paramount Pictures,200000000,28638131,674292608,1590450697,2264743305,19-Dec-97,"['Drama', 'Romance']",3 hr 14 min,PG-13
4,4,Star Wars: Episode VII - The Force Awakens,"As a new threat to the galaxy rises, Rey, a de...",2015,Walt Disney Studios Motion Pictures,245000000,247966675,936662225,1134647993,2071310218,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13

In [3]:
#display the number of rows and columns for the 'Holywd_gross_df' dataframe
Holywd_gross_df.shape

(1000, 14)

In [4]:
#printing the column names to refrence when editing the column names
Holywd_gross_df.columns

Index(['Unnamed: 0', 'Title', 'Movie Info', 'Year', 'Distributor',
       'Budget (in $)', 'Domestic Opening (in $)', 'Domestic Sales (in $)',
       'International Sales (in $)', 'World Wide Sales (in $)', 'Release Date',
       'Genre', 'Running Time', 'License'],
      dtype='object')

In [5]:
#printing the data types for each column to refrence when editing the data
Holywd_gross_df.dtypes

Unnamed: 0                     int64
Title                         object
Movie Info                    object
Year                           int64
Distributor                   object
Budget (in $)                 object
Domestic Opening (in $)       object
Domestic Sales (in $)          int64
International Sales (in $)     int64
World Wide Sales (in $)        int64
Release Date                  object
Genre                         object
Running Time                  object
License                       object
dtype: object

## Step 1: Removing the Duplicate "Unnamed" Column
The "Unnamed" column seems to be a **duplicate** of the index column and is unnescessary. The code below drops the column by identifying the specific column name.

In [6]:
#.drop() with the specified column name will remove the unwanted column
#inplace=True means that the modification is to the original DataFrame directly
Holywd_gross_df.drop(columns=['Unnamed: 0'], inplace=True)
#displaying the first 5 rows of the dataframe to verify the column was dropped
Holywd_gross_df.head()

,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License
0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000,1941066100,2799439100,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022,20th Century Studios,December 14 2022 (EMEA APAC),134100226,684075767,1636174514,2320250281,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
3,Titanic,A seventeen-year-old aristocrat falls in love ...,1997,Paramount Pictures,200000000,28638131,674292608,1590450697,2264743305,19-Dec-97,"['Drama', 'Romance']",3 hr 14 min,PG-13
4,Star Wars: Episode VII - The Force Awakens,"As a new threat to the galaxy rises, Rey, a de...",2015,Walt Disney Studios Motion Pictures,245000000,247966675,936662225,1134647993,2071310218,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13

## Step 2: Replace & Rearrange Headers
Some of the headers are a bit long and can be more precise. For example, several of the headers include "(in $)" for domestic sales... We can already assume that domestic sales are in U.S. dollars. For international and world wide sales, we can change it to something more professional looking such as (USD). Also, the "License" is actually displaying the movie rating, so I will change that column name to "Rating". I am also going to rearrange the headers so that similar information (such as dates) are closer together.

In [7]:
#replacing the header (column) names using a list
new_col_names = ['Title', 'Movie Info', 'Year', 'Distributor',
       'Budget', 'Domestic Opening', 'Domestic Sales',
       'International Sales (USD)', 'World Wide Sales (USD)', 'Release Date',
       'Genre', 'Running Time', 'Rating']
#assigning the new column names using the 'new_col_names' list
Holywd_gross_df.columns = new_col_names

In [8]:
#reordering the columns to organize more relavant/similar data together
Holywd_gross_df = Holywd_gross_df[['Title', 'Year', 'Release Date', 'Genre', 'Rating',  
       'Distributor', 'Running Time', 'Movie Info', 'Budget', 'Domestic Opening', 'Domestic Sales',
       'International Sales (USD)', 'World Wide Sales (USD)']]
#displaying the first 5 rows of the dataframe to verify the column names were changed and rearranged
Holywd_gross_df.head()

,Title,Year,Release Date,Genre,Rating,Distributor,Running Time,Movie Info,Budget,Domestic Opening,Domestic Sales,International Sales (USD),World Wide Sales (USD)
0,Avatar,2009,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",PG-13,Twentieth Century Fox,2 hr 42 min,A paraplegic Marine dispatched to the moon Pan...,237000000,77025481,785221649,2138484377,2923706026
1,Avengers: Endgame,2019,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,3 hr 1 min,After the devastating events of Avengers: Infi...,356000000,357115007,858373000,1941066100,2799439100
2,Avatar: The Way of Water,2022,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",PG-13,20th Century Studios,3 hr 1 min,Jake Sully lives with his newfound family form...,December 14 2022 (EMEA APAC),134100226,684075767,1636174514,2320250281
3,Titanic,1997,19-Dec-97,"['Drama', 'Romance']",PG-13,Paramount Pictures,3 hr 14 min,A seventeen-year-old aristocrat falls in love ...,200000000,28638131,674292608,1590450697,2264743305
4,Star Wars: Episode VII - The Force Awakens,2015,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,2 hr 18 min,"As a new threat to the galaxy rises, Rey, a de...",245000000,247966675,936662225,1134647993,2071310218

## Step 3: Handling Outliers/Bad Data Identified in the 'Budget' Column
At index 2 the 'budget' column shows "December 14 2022 (EMEA APAC)" insead of a numerical number representing the budget in USD. After expanding the dataframe to 50 rows, it shows that there are several rows that also have similar incorrect entries for the 'budget' column.

In [9]:
#the pd.to_numeric function attempts to convert the values in the "Budget" column to numeric format
#the errors='coerce' parameter replaces any values that cannot be converted to numeric with NaN 
Holywd_gross_df['Budget'] = pd.to_numeric(Holywd_gross_df['Budget'], errors='coerce')
#displaying the first 20 rows of the dataframe to verify the 'Budget" column now shows NaN for non-numeric entries
Holywd_gross_df.head(20)

,Title,Year,Release Date,Genre,Rating,Distributor,Running Time,Movie Info,Budget,Domestic Opening,Domestic Sales,International Sales (USD),World Wide Sales (USD)
0,Avatar,2009,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",PG-13,Twentieth Century Fox,2 hr 42 min,A paraplegic Marine dispatched to the moon Pan...,237000000.0,77025481,785221649,2138484377,2923706026
1,Avengers: Endgame,2019,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,3 hr 1 min,After the devastating events of Avengers: Infi...,356000000.0,357115007,858373000,1941066100,2799439100
2,Avatar: The Way of Water,2022,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",PG-13,20th Century Studios,3 hr 1 min,Jake Sully lives with his newfound family form...,NaN,134100226,684075767,1636174514,2320250281
3,Titanic,1997,19-Dec-97,"['Drama', 'Romance']",PG-13,Paramount Pictures,3 hr 14 min,A seventeen-year-old aristocrat falls in love ...,200000000.0,28638131,674292608,1590450697,2264743305
4,Star Wars: Episode VII - The Force Awakens,2015,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,2 hr 18 min,"As a new threat to the galaxy rises, Rey, a de...",245000000.0,247966675,936662225,1134647993,2071310218
5,Avengers: Infinity War,2018,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,2 hr 18 min,The Avengers and their allies must be willing ...,NaN,257698183,678815482,1373599557,2052415039
6,Spider-Man: No Way Home,2021,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Sony Pictures Entertainment (SPE),2 hr 18 min,"With Spider-Man's identity now revealed, Peter...",NaN,260138569,814115070,1107732041,1921847111
7,Jurassic World,2015,10-Jun-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Universal Pictures,2 hr 4 min,"A new theme park, built on the original site o...",150000000.0,208806270,653406625,1018130819,1671537444
8,The Lion King,2019,11-Jul-19,"['Adventure', 'Drama', 'Family', 'Musical']",PG,Walt Disney Studios Motion Pictures,1 hr 58 min,"After the murder of his father, a young lion p...",260000000.0,191770759,543638043,1119437358,1663075401
9,The Avengers,2012,25-Apr-12,"['Action', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,2 hr 23 min,Earth's mightiest heroes must come together an...,220000000.0,207438708,623357910,897180626,1520538536
10,Furious 7,2015,1-Apr-15,"['Action', 'Crime', 'Thriller']",PG-13,Universal Pictures,2 hr 17 min,Deckard Shaw seeks revenge against Dominic Tor...,190000000.0,147187040,353007020,1162334379,1515341399
11,Top Gun: Maverick,2022,1-Apr-15,"['Action', 'Crime', 'Thriller']",PG-13,Paramount Pictures,2 hr 17 min,"After thirty years, Maverick is still pushing ...",NaN,126707459,718732821,776963471,1495696292
12,Frozen II,2019,20-Nov-19,"['Adventure', 'Animation', 'Comedy', 'Drama', ...",PG,Walt Disney Studios Motion Pictures,1 hr 43 min,"Anna, Elsa, Kristoff, Olaf and Sven leave Aren...",150000000.0,130263358,477373578,976309898,1453683476
13,Barbie,2023,20-Nov-19,"['Adventure', 'Animation', 'Comedy', 'Drama', ...",PG,Warner Bros.,1 hr 43 min,Barbie suffers a crisis that leads her to ques...,NaN,162022044,630450087,797000000,1427450087
14,Avengers: Age of Ultron,2015,22-Apr-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,2 hr 21 min,When Tony Stark and Bruce Banner try to jump-s...,250000000.0,191271109,459005868,946012180,1405018048
15,The Super Mario Bros. Movie,2023,22-Apr-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Universal Pictures,2 hr 21 min,A plumber named Mario travels through an under...,NaN,146361865,574934330,785829724,1360764054
16,Black Panther,2018,22-Apr-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,2 hr 21 min,"T'Challa, heir to the hidden but advanced king...",NaN,202003951,700426566,649499517,1349926083
17,Harry Potter and the Deathly Hallows: Part 2,2011,22-Apr-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Warner Bros.,2 hr 21 min,"Harry, Ron, and Hermione search for Voldemort'...",NaN,169189427,381447587,960912354,1342359942
18,Star Wars: Episode VIII - The Last Jedi,2017,13-Dec-17,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,2 hr 32 min,The Star Wars saga continues as new heroes and...,317000000.0,220009584,620181382,714226324,1334407706
19,Jurassic World: Fallen Kingdom,2018,6-Jun-18,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Universal Pictures,2 hr 8 min,When the island's dormant volcano begins roari...,170000000.0,148024610,417719760,892746536,1310466296

## Step 4: Finding Duplicates
Having duplicates of the same movie might make it difficult to analyze this data later on. First we will find the movies that have duplicates in the "title" column. Then we will need to investigate whether these duplicates are a duplicate entry of the data, or if there is actually more than one movie with the same name.

In [10]:
#creating an array of unique movie titles that are duplicated in the DataFrame
#.duplicated() method with the subset='title' parameter checks for duplicate values in the "title" column
#the keep=False parameter marks all instances of the duplicated titles as True
duplicate_titles = Holywd_gross_df[Holywd_gross_df.duplicated(subset='Title', keep=False)]['Title'].unique()
#printing the array of duplicated titles
print(duplicate_titles)

['The Lion King' 'Beauty and the Beast' 'Aladdin' 'The Jungle Book'
 'The Little Mermaid' 'Godzilla' 'Teenage Mutant Ninja Turtles'
 'The Mummy' 'Ghostbusters' 'Total Recall' 'Hercules' 'The Addams Family']

In [11]:
#calculating the total number of duplicated titles using .sum()
duplicate_count = Holywd_gross_df.duplicated(subset='Title').sum()
print("The number of duplicated rows based on the 'Title' column is:", duplicate_count)

The number of duplicated rows based on the 'Title' column is: 12

In [12]:
#displaying each of the duplicated rows for further investigation...
#.isin() checks for the presence of each title in the array of duplicate_titles 
#the result is a boolean mask that selects the rows where the condition is True
duplicate_rows = Holywd_gross_df[Holywd_gross_df['Title'].isin(duplicate_titles)]
#displaying the full row for the duplicated titles
print(duplicate_rows)

                            Title  Year Release Date  \
8                   The Lion King  2019    11-Jul-19
21           Beauty and the Beast  2017    16-Mar-17
42                        Aladdin  2019    22-May-19
56                  The Lion King  1994    15-Jun-94
57                The Jungle Book  2016     7-Apr-16
195            The Little Mermaid  2023    11-Feb-15
225                      Godzilla  2014    14-May-14
235                       Aladdin  1992    13-Nov-92
250  Teenage Mutant Ninja Turtles  2014     7-Aug-14
315          Beauty and the Beast  1991    15-Nov-91
321                     The Mummy  1999     7-May-99
331                     The Mummy  2017     6-Jun-17
377                      Godzilla  1998    20-May-98
556                  Ghostbusters  1984     8-Jun-84
631                  Total Recall  1990     1-Jun-90
657                      Hercules  1997    15-Jun-97
689                      Hercules  2014    23-Jul-14
741                  Ghostbusters  2016    11-Jul-16
835            The Little Mermaid  1989    16-Dec-04
856               The Jungle Book  1967     5-Dec-06
869             The Addams Family  2019    11-Oct-19
882  Teenage Mutant Ninja Turtles  1990    30-Mar-90
898                  Total Recall  2012     2-Aug-12
931             The Addams Family  1991    22-Nov-91

                                                 Genre Rating  \
8          ['Adventure', 'Drama', 'Family', 'Musical']     PG
21   ['Adventure', 'Family', 'Fantasy', 'Musical', ...     PG
42   ['Adventure', 'Comedy', 'Family', 'Fantasy', '...     PG
56   ['Adventure', 'Animation', 'Drama', 'Family', ...      G
57         ['Adventure', 'Drama', 'Family', 'Fantasy']     PG
195                   ['Drama', 'Romance', 'Thriller']      R
225      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  PG-13
235  ['Adventure', 'Animation', 'Comedy', 'Family',...    NaN
250        ['Action', 'Adventure', 'Comedy', 'Sci-Fi']  PG-13
315  ['Animation', 'Family', 'Fantasy', 'Musical', ...    NaN
321                 ['Action', 'Adventure', 'Fantasy']  PG-13
331  ['Action', 'Adventure', 'Fantasy', 'Horror', '...  PG-13
377                   ['Action', 'Sci-Fi', 'Thriller']  PG-13
556          ['Action', 'Comedy', 'Fantasy', 'Sci-Fi']    NaN
631                  ['Action', 'Adventure', 'Sci-Fi']    NaN
657  ['Adventure', 'Animation', 'Comedy', 'Family',...    NaN
689                 ['Action', 'Adventure', 'Fantasy']  PG-13
741          ['Action', 'Comedy', 'Fantasy', 'Sci-Fi']  PG-13
835       ['Adventure', 'Comedy', 'Family', 'Fantasy']     PG
856                              ['Comedy', 'Romance']  PG-13
869  ['Animation', 'Comedy', 'Family', 'Fantasy', '...     PG
882  ['Action', 'Adventure', 'Comedy', 'Family', 'S...    NaN
898      ['Action', 'Adventure', 'Sci-Fi', 'Thriller']  PG-13
931                              ['Comedy', 'Fantasy']    NaN

                             Distributor Running Time  \
8    Walt Disney Studios Motion Pictures  1 hr 58 min
21   Walt Disney Studios Motion Pictures   2 hr 9 min
42   Walt Disney Studios Motion Pictures   2 hr 8 min
56   Walt Disney Studios Motion Pictures  1 hr 28 min
57   Walt Disney Studios Motion Pictures  1 hr 46 min
195  Walt Disney Studios Motion Pictures   2 hr 5 min
225                         Warner Bros.   2 hr 3 min
235  Walt Disney Studios Motion Pictures  1 hr 30 min
250                   Paramount Pictures  1 hr 41 min
315  Walt Disney Studios Motion Pictures  1 hr 24 min
321                   Universal Pictures   2 hr 4 min
331                   Universal Pictures  1 hr 51 min
377    Sony Pictures Entertainment (SPE)  2 hr 19 min
556                    Columbia Pictures  1 hr 45 min
631    Sony Pictures Entertainment (SPE)  1 hr 53 min
657  Walt Disney Studios Motion Pictures  1 hr 33 min
689                   Paramount Pictures  1 hr 38 min
741    Sony Pictures Entertainment (SPE)  1 hr 57 min
835  Walt Disney Studios Motion Pictures  1 hr 48 min
856  Walt Disney Studios Motion Pictures  2 hr 16 min
869             United Artists Releasing  1 hr 26 min
882                      New Line Cinema  1 hr 33 min
898    Sony Pictures Entertainment (SPE)  1 hr 58 min
931                   Paramount Pictures  1 hr 39 min

                                            Movie Info       Budget  \
8    After the murder of his father, a young lion p...  260000000.0
21   A selfish Prince is cursed to become a monster...  160000000.0
42   A kind-hearted street urchin and a power-hungr...  183000000.0
56   Lion prince Simba and his father are targeted ...   45000000.0
57   After a threat from the tiger Shere Khan force...  175000000.0
195  A young mermaid makes a deal with a sea witch ...          NaN
225  The world is beset by the appearance of monstr...  160000000.0
235  A kind-hearted street urchin and a power-hungr...   28000000.0
250  When a kingpin threatens New York City, a grou...  125000000.0
315  A prince cursed to spend his days as a hideous...   25000000.0
321  At an archaeological dig in the ancient city o...   80000000.0
331  An ancient Egyptian princess is awakened from ...  125000000.0
377  French nuclear tests irradiate an iguana into ...  130000000.0
556  Three parapsychologists forced out of their un...   30000000.0
631  When a man goes in to have virtual vacation me...   65000000.0
657  The son of Zeus and Hera is stripped of his im...   85000000.0
689  Having endured his legendary twelve labors, He...  100000000.0
741  Following a ghost invasion of Manhattan, paran...  144000000.0
835  A mermaid princess makes a Faustian bargain in...          NaN
856  Bagheera the Panther and Baloo the Bear have a...   85000000.0
869  The eccentrically macabre family moves to a bl...   24000000.0
882  Four teenage mutant ninja turtles emerge from ...   13500000.0
898  A factory worker, Douglas Quaid, begins to sus...  125000000.0
931  Con artists plan to fleece an eccentric family...   30000000.0

               Domestic Opening  Domestic Sales  International Sales (USD)  \
8                     191770759       543638043                 1119437358
21                    174750616       504481165                  761634799
42                     91500929       355559216                  698744784
56                      1586753       422783777                  545728028
57                    103261464       364001123                  603723652
195                    95578040       298172056                  271420242
225                    93188384       200676069                  324300000
235                      196664       217350219                  286700000
250                    65575105       191204754                  293800000
315                      162146       218967620                  186043788
321                    43369635       155385488                  260547918
331                    31688375        80227895                  329003712
377                    44047541       136314294                  242700000
556                    13578151       243578797                   53000000
631                    25533700       119412921                  141905000
657                      249567        99112101                  153600000
689                    29800263        72688614                  172131248
741                    46018755       128350574                  100796935
835                     6031914       111543479                   99800000
856  October 18 1967 (Domestic)       141843612                   64000000
869                    30300007       100723831                  103670352
882                    25398367       135384756                   66700000
898                    25577758        58877969                  139589199
931                    24203754       113502426                   78000000

     World Wide Sales (USD)
8                1663075401
21               1266115964
42               1054304000
56                968511805
57                967724775
195               569592298
225               524976069
235               504050219
250               485004754
315               424967620
321               415933406
331               409231607
377               379014294
556               296578797
631               261317921
657               252712101
689               244819862
741               229147509
835               211343479
856               205843612
869               204394183
882               202084756
898               198467168
931               191502426

In [13]:
#printing a subset of the data where both the "title" and "date" columns are duplicates
duplicate_subset = Holywd_gross_df[Holywd_gross_df.duplicated(subset=['Title', 'Year'], keep=False)]
print(duplicate_subset)
#the results are an empty dataframe, which means that NONE of the rows are a duplicate entry of the data

Empty DataFrame
Columns: [Title, Year, Release Date, Genre, Rating, Distributor, Running Time, Movie Info, Budget, Domestic Opening, Domestic Sales, International Sales (USD), World Wide Sales (USD)]
Index: []

## Step 5: Editing Duplicate Movie Titles
Based on the results above, none of the rows are exact duplicate entries of the data. If there were duplicate entries of the data, we could remove those rows using the .drop() method. However, it seems that our duplicate movie titles are movies that have been remade years later. In this instance one option is to identify the remake movies with "(Remake)" added to the end of the title.

In [14]:
#creating a Series 'duplicate_titles' containing the titles that are duplicated in the 'Title' column
duplicate_titles = Holywd_gross_df[Holywd_gross_df.duplicated(subset='Title', keep=False)]['Title']
#filters so that the series only includes Series the titles that are duplicated and ignores the first occurance of the title
titles_to_rename = duplicate_titles[duplicate_titles.duplicated(keep='first')]

#a loop that iterates through each title in the titles_to_rename
for title in titles_to_rename:
    #the code retrieves the indices of the rows where the 'Title' column matches the current title
    indices = Holywd_gross_df[Holywd_gross_df['Title'] == title].index
    #a loop that for each index in the indices list, starting from the second index (index 1) 
    for i in range(1, len(indices)):
        #the code updates the 'Title' column of the DataFrame at the specified index by appending "(Remake)" to the current title
        Holywd_gross_df.at[indices[i], 'Title'] = f"{title} (Remake)"

In [15]:
subset_by_indexes = Holywd_gross_df.iloc[689]
print(subset_by_indexes)

Title                                                        Hercules (Remake)
Year                                                                      2014
Release Date                                                         23-Jul-14
Genre                                       ['Action', 'Adventure', 'Fantasy']
Rating                                                                   PG-13
Distributor                                                 Paramount Pictures
Running Time                                                       1 hr 38 min
Movie Info                   Having endured his legendary twelve labors, He...
Budget                                                             100000000.0
Domestic Opening                                                      29800263
Domestic Sales                                                        72688614
International Sales (USD)                                            172131248
World Wide Sales (USD)                                               244819862
Name: 689, dtype: object

In [16]:
#locating "The Mummy" and "Hercules" by thier index 
rows_to_print = Holywd_gross_df.loc[[321, 331, 657, 689]]
#Diplaying the indexed data to see that the duplicate movie title now contains (Remake)
print(rows_to_print)

                  Title  Year Release Date  \
321           The Mummy  1999     7-May-99
331  The Mummy (Remake)  2017     6-Jun-17
657            Hercules  1997    15-Jun-97
689   Hercules (Remake)  2014    23-Jul-14

                                                 Genre Rating  \
321                 ['Action', 'Adventure', 'Fantasy']  PG-13
331  ['Action', 'Adventure', 'Fantasy', 'Horror', '...  PG-13
657  ['Adventure', 'Animation', 'Comedy', 'Family',...    NaN
689                 ['Action', 'Adventure', 'Fantasy']  PG-13

                             Distributor Running Time  \
321                   Universal Pictures   2 hr 4 min
331                   Universal Pictures  1 hr 51 min
657  Walt Disney Studios Motion Pictures  1 hr 33 min
689                   Paramount Pictures  1 hr 38 min

                                            Movie Info       Budget  \
321  At an archaeological dig in the ancient city o...   80000000.0
331  An ancient Egyptian princess is awakened from ...  125000000.0
657  The son of Zeus and Hera is stripped of his im...   85000000.0
689  Having endured his legendary twelve labors, He...  100000000.0

    Domestic Opening  Domestic Sales  International Sales (USD)  \
321         43369635       155385488                  260547918
331         31688375        80227895                  329003712
657           249567        99112101                  153600000
689         29800263        72688614                  172131248

     World Wide Sales (USD)
321               415933406
331               409231607
657               252712101
689               244819862

## Step 6: Editing Monetary Values into a More Readable Format
Currently the monetary values for the 'Budget', 'Domestic Opening', 'Domestic Sales', 'International Sales (USD)', and 'World Wide Sales (USD)' columns are displayed as a long list of numbers such as: 1453683476. In order to change the monetary values to a more readable format I will need to first convert each of the columns to a numeric format, then format the numeric values to US currency. I will need to be conscious that the "Budget" column contains NaN values due to removing bad data earlier, so I will have to tell the code to "ignore" those NaN values.

In [17]:
#importing the locale module which can be used to format numbers and currencies
import locale

#setting the locale to the United States (since our monetary values are in USD)
#the LC_ALL constant represents all categories of the locale
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

#create a list of columns to format
columns_to_format = ['Budget', 'Domestic Opening', 'Domestic Sales', 'International Sales (USD)', 'World Wide Sales (USD)']

#converting the columns to numeric format and formatting the values
#a for loop that iterates through each column in the columns_to_format list
for col in columns_to_format:
    #converts the column values to numeric using pd.to_numeric(), with errors coerced to NaN
    Holywd_gross_df[col] = pd.to_numeric(Holywd_gross_df[col], errors='coerce')
    #applying a lambda function to format the numeric values as currency using the locale.currency
    #the grouping parameter set to True to include the grouping separator
    #if a NaN value is encountered, it is ignored
    Holywd_gross_df[col] = Holywd_gross_df[col].apply(lambda x: locale.currency(x, grouping=True) if not np.isnan(x) else np.nan)

In [18]:
#dipslaying the dataframe to verify the columns with monetary values have changed
Holywd_gross_df.head()

,Title,Year,Release Date,Genre,Rating,Distributor,Running Time,Movie Info,Budget,Domestic Opening,Domestic Sales,International Sales (USD),World Wide Sales (USD)
0,Avatar,2009,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",PG-13,Twentieth Century Fox,2 hr 42 min,A paraplegic Marine dispatched to the moon Pan...,"$237,000,000.00","$77,025,481.00","$785,221,649.00","$2,138,484,377.00","$2,923,706,026.00"
1,Avengers: Endgame,2019,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,3 hr 1 min,After the devastating events of Avengers: Infi...,"$356,000,000.00","$357,115,007.00","$858,373,000.00","$1,941,066,100.00","$2,799,439,100.00"
2,Avatar: The Way of Water,2022,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",PG-13,20th Century Studios,3 hr 1 min,Jake Sully lives with his newfound family form...,NaN,"$134,100,226.00","$684,075,767.00","$1,636,174,514.00","$2,320,250,281.00"
3,Titanic,1997,19-Dec-97,"['Drama', 'Romance']",PG-13,Paramount Pictures,3 hr 14 min,A seventeen-year-old aristocrat falls in love ...,"$200,000,000.00","$28,638,131.00","$674,292,608.00","$1,590,450,697.00","$2,264,743,305.00"
4,Star Wars: Episode VII - The Force Awakens,2015,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",PG-13,Walt Disney Studios Motion Pictures,2 hr 18 min,"As a new threat to the galaxy rises, Rey, a de...","$245,000,000.00","$247,966,675.00","$936,662,225.00","$1,134,647,993.00","$2,071,310,218.00"

## Displaying the Human Readable Dataset:

In [19]:
#displaying all 1000 rows of the dataset
pd.set_option('display.max_rows', None)
Holywd_gross_df

                                                 Title  Year Release Date  \
0                                               Avatar  2009    16-Dec-09
1                                    Avengers: Endgame  2019    24-Apr-19
2                             Avatar: The Way of Water  2022    24-Apr-19
3                                              Titanic  1997    19-Dec-97
4           Star Wars: Episode VII - The Force Awakens  2015    16-Dec-15
5                               Avengers: Infinity War  2018    16-Dec-15
6                              Spider-Man: No Way Home  2021    16-Dec-15
7                                       Jurassic World  2015    10-Jun-15
8                                        The Lion King  2019    11-Jul-19
9                                         The Avengers  2012    25-Apr-12
10                                           Furious 7  2015     1-Apr-15
11                                   Top Gun: Maverick  2022     1-Apr-15
12                                           Frozen II  2019    20-Nov-19
13                                              Barbie  2023    20-Nov-19
14                             Avengers: Age of Ultron  2015    22-Apr-15
15                         The Super Mario Bros. Movie  2023    22-Apr-15
16                                       Black Panther  2018    22-Apr-15
17        Harry Potter and the Deathly Hallows: Part 2  2011    22-Apr-15
18             Star Wars: Episode VIII - The Last Jedi  2017    13-Dec-17
19                      Jurassic World: Fallen Kingdom  2018     6-Jun-18
20                                              Frozen  2013    22-Nov-13
21                                Beauty and the Beast  2017    16-Mar-17
22                                       Incredibles 2  2018    16-Mar-17
23                             The Fate of the Furious  2017    12-Apr-17
24                                          Iron Man 3  2013    24-Apr-13
25                                             Minions  2015     9-Apr-15
26                          Captain America: Civil War  2016    27-Apr-16
27                                             Aquaman  2018    27-Apr-16
28       The Lord of the Rings: The Return of the King  2003    17-Dec-03
29                                             Skyfall  2012    25-Oct-12
30                           Spider-Man: Far from Home  2019    28-Jun-19
31                                      Captain Marvel  2019     6-Mar-19
32                      Transformers: Dark of the Moon  2011    29-Jun-11
33                                       Jurassic Park  1993    11-Jun-93
34                     Transformers: Age of Extinction  2014    25-Jun-14
35                               The Dark Knight Rises  2012    19-Jul-12
36       Star Wars: Episode IX - The Rise of Skywalker  2019    18-Dec-19
37                                               Joker  2019     2-Oct-19
38                                         Toy Story 4  2019    20-Jun-19
39                                         Toy Story 3  2010    16-Jun-10
40          Pirates of the Caribbean: Dead Man's Chest  2006     6-Jul-06
41                        Rogue One: A Star Wars Story  2016    14-Dec-16
42                                             Aladdin  2019    22-May-19
43         Pirates of the Caribbean: On Stranger Tides  2011    18-May-11
44                                     Despicable Me 3  2017    14-Jun-17
45                                        Finding Dory  2016    14-Jun-17
46           Star Wars: Episode I - The Phantom Menace  1999    19-May-99
47                                            Zootopia  2016    19-May-99
48                                 Alice in Wonderland  2010     3-Mar-10
49               Harry Potter and the Sorcerer's Stone  2001    16-Nov-01
50                   The Hobbit: An Unexpected Journey  2012    16-Nov-01
51                                     The Dark Knight  2008    16-Jul-08
52                             Jurassic World Dominion  2022    16-Jul-08
53                      Jumanji: Welcome to the Jungle  2017    20-Dec-17
54        Harry Potter and the Deathly Hallows: Part 1  2010    20-Dec-17
55                                     Despicable Me 2  2013    20-Jun-13
56                              The Lion King (Remake)  1994    15-Jun-94
57                                     The Jungle Book  2016     7-Apr-16
58           The Hobbit: The Battle of the Five Armies  2014     7-Apr-16
59            Pirates of the Caribbean: At World's End  2007    22-May-07
60                 The Hobbit: The Desolation of Smaug  2013    22-May-07
61         Doctor Strange in the Multiverse of Madness  2022    22-May-07
62               The Lord of the Rings: The Two Towers  2002    18-Dec-02
63           Harry Potter and the Order of the Phoenix  2007    11-Jul-07
64                                        Finding Nemo  2003    30-May-03
65                            Minions: The Rise of Gru  2022    30-May-03
66              Harry Potter and the Half-Blood Prince  2009    15-Jul-09
67                                             Shrek 2  2004    19-May-04
68                                         Oppenheimer  2023    19-May-04
69             Harry Potter and the Chamber of Secrets  2002    14-Nov-02
70                                   Bohemian Rhapsody  2018    26-Oct-18
71                         The Battle at Lake Changjin  2021    26-Oct-18
72   The Lord of the Rings: The Fellowship of the Ring  2001    19-Dec-01
73                 Harry Potter and the Goblet of Fire  2005    16-Nov-05
74                                        Spider-Man 3  2007     1-May-07
75                             The Secret Life of Pets  2016    24-Jun-16
76                      Ice Age: Dawn of the Dinosaurs  2009    29-Jun-09
77                                             Spectre  2015    26-Oct-15
78                              Spider-Man: Homecoming  2017     5-Jul-17
79                          Ice Age: Continental Drift  2012    27-Jun-12
80                  Batman v Superman: Dawn of Justice  2016    23-Mar-16
81                                      Wolf Warrior 2  2017    27-Jul-17
82        Star Wars: Episode III - Revenge of the Sith  2005    18-May-05
83                     The Hunger Games: Catching Fire  2013    15-Nov-13
84                      Guardians of the Galaxy Vol. 2  2017    25-Apr-17
85                      Black Panther: Wakanda Forever  2022    25-Apr-17
86                                          Inside Out  2015    10-Jun-15
87                                               Venom  2018     3-Oct-18
88                                      Thor: Ragnarok  2017    24-Oct-17
89           The Twilight Saga: Breaking Dawn - Part 2  2012    14-Nov-12
90                      Guardians of the Galaxy Vol. 3  2023    14-Nov-12
91                                           Inception  2010    15-Jul-10
92                 Transformers: Revenge of the Fallen  2009    19-Jun-09
93                                          Spider-Man  2002     3-May-02
94                                        Wonder Woman  2017    30-May-17
95                                             Hi, Mom  2021    30-May-17
96                                    Independence Day  1996     3-Jul-96
97                                                Coco  2017     3-Jul-96
98             Fantastic Beasts and Where to Find Them  2016    16-Nov-16
99                                     Shrek the Third  2007    17-May-07
100                            Jumanji: The Next Level  2019     4-Dec-19
101           Harry Potter and the Prisoner of Azkaban  2004     2-Jun-04
102   Pirates of the Caribbean: Dead Men Tell No Tales  2017    24-May-17
103                         E.T. the Extra-Terrestrial  1982    11-Jun-82
104                      Mission: Impossible - Fallout  2018    25-Jul-18
105                                               2012  2009    11-Nov-09
106  Indiana Jones and the Kingdom of the Crystal S...  2008    21-May-08
107                                       Spider-Man 2  2004    30-Jun-04
108                                   Fast & Furious 6  2013    17-May-13
109                                         Deadpool 2  2018    16-May-18
110                                           Deadpool  2016     9-Feb-16
111                 Star Wars: Episode IV - A New Hope  1977    25-May-77
112                                     No Time to Die  2021    25-May-77
113                            Guardians of the Galaxy  2014    30-Jul-14
114                                         The Batman  2022    30-Jul-14
115                             Thor: Love and Thunder  2022    30-Jul-14
116              Fast & Furious Presents: Hobbs & Shaw  2019     1-Jul-19
117                                  The Da Vinci Code  2006    17-May-06
118                                         Maleficent  2014    28-May-14
119                             The Amazing Spider-Man  2012    28-Jun-12
120              The Hunger Games: Mockingjay - Part 1  2014    19-Nov-14
121                                Shrek Forever After  2010    20-May-10
122                                            Gravity  2013     3-Oct-13
123                 Madagascar 3: Europe's Most Wanted  2012     6-Jun-12
124                                      Suicide Squad  2016     3-Aug-16
125                         X-Men: Days of Future Past  2014    21-May-14
126  The Chronicles of Narnia: The Lion, the Witch ...  2005     7-Dec-05
127                                Monsters University  2013     7-Dec-05
128                                The Matrix Reloaded  2003    15-May-03
129                                                 Up  2009    28-May-09
130                                             Ne Zha  2019    28-May-09
131                                  F9: The Fast Saga  2021    28-May-09
132                Captain America: The Winter Soldier  2014    26-Mar-14
133          The Twilight Saga: Breaking Dawn - Part 1  2011    16-Nov-11
134                        The Twilight Saga: New Moon  2009    18-Nov-09
135                     Dawn of the Planet of the Apes  2014     9-Jul-14
136                                       Transformers  2007    28-Jun-07
137                           The Amazing Spider-Man 2  2014    28-Jun-07
138                                             Fast X  2023    28-Jun-07
139                                       Interstellar  2014     5-Nov-14
140                                                 It  2017     6-Sep-17
141                                The Wandering Earth  2019     6-Sep-17
142                         The Twilight Saga: Eclipse  2010    30-Jun-10
143               Mission: Impossible - Ghost Protocol  2011    14-Dec-11
144                                         Mamma Mia!  2008    27-Jun-08
145                                   The Hunger Games  2012     8-Mar-12
146                Spider-Man: Across the Spider-Verse  2023     8-Mar-12
147                                              Moana  2016     8-Mar-12
148                              Detective Chinatown 3  2021     8-Mar-12
149                 Mission: Impossible - Rogue Nation  2015    24-Jul-15
150                                       Forrest Gump  1994     6-Jul-94
151                                     Doctor Strange  2016    25-Oct-16
152                                    The Sixth Sense  1999     6-Aug-99
153                                       Man of Steel  2013    12-Jun-13
154                              Ice Age: The Meltdown  2006    29-Mar-06
155                                    Kung Fu Panda 2  2011    26-May-11
156                                     Justice League  2017    26-May-11
157                                         Big Hero 6  2014    25-Oct-14
158        Fantastic Beasts: The Crimes of Grindelwald  2018    12-Oct-18
159  Pirates of the Caribbean: The Curse of the Bla...  2003     9-Jul-03
160                                     Men in Black 3  2012    23-May-12
161       Star Wars: Episode II - Attack of the Clones  2002    16-May-02
162              The Hunger Games: Mockingjay - Part 2  2015    18-Nov-15
163                               Thor: The Dark World  2013    30-Oct-13
164                                               Sing  2016     2-Dec-16
165                                      Kung Fu Panda  2008     5-Jun-08
166                                    The Incredibles  2004     5-Nov-04
167                                        The Martian  2015    30-Sep-15
168                                            Hancock  2008     2-Jul-08
169                                  Water Gate Bridge  2022     2-Jul-08
170                                          Fast Five  2011    20-Apr-11
171                                         Iron Man 2  2010    28-Apr-10
172                                        Ratatouille  2007    28-Jun-07
173                               Ant-Man and the Wasp  2018    28-Jun-07
174                         How to Train Your Dragon 2  2014     5-Jun-14
175                                              Logan  2017     1-Mar-17
176                      The Lost World: Jurassic Park  1997    23-May-97
177                                      Casino Royale  2006    15-Nov-06
178                          The Passion of the Christ  2004    25-Feb-04
179                                         Life of Pi  2012    21-Nov-12
180                                   Ready Player One  2018    28-Mar-18
181                      Transformers: The Last Knight  2017    21-Jun-17
182                        Madagascar: Escape 2 Africa  2008    30-Oct-08
183                                  War of the Worlds  2005    29-Jun-05
184                                            Tangled  2010    24-Nov-10
185                                  Quantum of Solace  2008    31-Oct-08
186                                       Men in Black  1997     2-Jul-97
187                                         The Croods  2013    15-Mar-13
188                               The Hangover Part II  2011    25-May-11
189                                           Iron Man  2008    30-Apr-08
190                                        I Am Legend  2007    12-Dec-07
191                                     Monsters, Inc.  2001     2-Nov-01
192                                  Operation Red Sea  2018     2-Nov-01
193                                Night at the Museum  2006     2-Nov-01
194                               Fifty Shades of Grey  2015    11-Feb-15
195                                 The Little Mermaid  2023    11-Feb-15
196      Mission: Impossible - Dead Reckoning Part One  2023     8-Jul-23
197                                 Kong: Skull Island  2017     8-Mar-17
198                                         The Smurfs  2011    27-Jul-11
199                                             Cars 2  2011    22-Jun-11
200                                          King Kong  2005    14-Dec-05
201                                      Puss in Boots  2011    27-Oct-11
202                                        The Mermaid  2016    27-Oct-11
203                                         Armageddon  1998     1-Jul-98
204                             The Day After Tomorrow  2004    26-May-04
205                                                Ted  2012    29-Jun-12
206                                    American Sniper  2014    25-Dec-14
207                             Mission: Impossible II  2000    24-May-00
208                              Detective Chinatown 2  2018    24-May-00
209                                  X-Men: Apocalypse  2016    18-May-16
210                 Sherlock Holmes: A Game of Shadows  2011    18-May-16
211                                      Despicable Me  2010     8-Jul-10
212                                         Cinderella  2015    11-Mar-15
213                                         Madagascar  2005    11-Mar-15
214                                        World War Z  2013    19-Jun-13
215                                              Brave  2012    21-Jun-12
216     Star Wars: Episode V - The Empire Strikes Back  1980    21-May-80
217                                 The Simpsons Movie  2007    25-Jul-07
218                                       The Revenant  2015    25-Dec-15
219                                            The Meg  2018     8-Aug-18
220                          Ralph Breaks the Internet  2018    21-Nov-18
221              Hotel Transylvania 3: Summer Vacation  2018    28-Jun-18
222                                      The Boss Baby  2017    28-Jun-18
223                                            Dunkirk  2017    19-Jul-17
224                                         The Grinch  2018     7-Nov-18
225                                           Godzilla  2014    14-May-14
226         How to Train Your Dragon: The Hidden World  2019     3-Jan-19
227                                    Sherlock Holmes  2009     1-Jan-09
228                                   Meet the Fockers  2004    22-Dec-04
229                                             WALL·E  2008    26-Jun-08
230                                    Kung Fu Panda 3  2016    28-Jan-16
231                         Terminator 2: Judgment Day  1991     3-Jul-91
232                                            Ant-Man  2015    10-Jul-15
233                        Venom: Let There Be Carnage  2021    10-Jul-15
234                                              Ghost  1990    13-Jul-90
235                                   Aladdin (Remake)  1992    13-Nov-92
236                                          Gladiator  2000     4-May-00
237                                              Rio 2  2014    20-Mar-14
238                                               Troy  2004    12-May-04
239                                        Toy Story 2  1999    19-Nov-99
240                           How to Train Your Dragon  2010    18-Mar-10
241                                            Twister  1996    10-May-96
242                          Oz the Great and Powerful  2013     6-Mar-13
243                                Clash of the Titans  2010    31-Mar-10
244                       Maleficent: Mistress of Evil  2019    16-Oct-19
245                     War for the Planet of the Apes  2017    11-Jul-17
246                                              Shrek  2001    16-May-01
247                                   Mr. & Mrs. Smith  2005     8-Jun-05
248                                          Elemental  2023     8-Jun-05
249                                    Angels & Demons  2009    13-May-09
250                       Teenage Mutant Ninja Turtles  2014     7-Aug-14
251                                     Bruce Almighty  2003    23-May-03
252                                  The King's Speech  2010    26-Nov-10
253                                                Rio  2011     4-Apr-11
254                                Saving Private Ryan  1998    24-Jul-98
255                     Rise of the Planet of the Apes  2011     3-Aug-11
256                       Puss in Boots: The Last Wish  2022     3-Aug-11
257                                         Home Alone  1990    16-Nov-90
258                                               Jaws  1975    20-Jun-75
259                  Ant-Man and the Wasp: Quantumania  2023    20-Jun-75
260                               Hotel Transylvania 2  2015    21-Sep-15
261         Star Wars: Episode VI - Return of the Jedi  1983    25-May-83
262                  Charlie and the Chocolate Factory  2005    14-Jul-05
263                 Indiana Jones and the Last Crusade  1989    24-May-89
264                                        San Andreas  2015    22-May-15
265                                     It Chapter Two  2019     4-Sep-19
266                                         La La Land  2016     8-Dec-16
267                                     Wreck-It Ralph  2012     1-Nov-12
268                                  Godzilla vs. Kong  2021     1-Nov-12

## Summary:

&emsp; **What changes were made to the data?** I made 6 cleaning/formatting changes to the flat file data. These include removing duplicate columns, replacing and rearranging headers, handling bad data from the 'Budget' column, finding duplicate entries, editing duplicate movie titles, and editing monetary values into a more readable format.  

&emsp; **Did you make any assumptions in cleaning/transforming the data?** One of the assumptions that I made was that duplicate movie titles in this data were a result of movies that have been remade years later. I also made the assumption that "sales in $" stood for sales in USD, which caused me to format the monetary values to USD. A third assumption that I made was that the non-numerical values in the "Budget" column were an error during the data entry. Without further context on what those entries were, I had to make the decision to change those values to NaN. 

&emsp; **What risks could be created based on the transformations done?** The main risk is that there might be an error in my coding that I did not notice, which might cause the data to be inaccurately calculated or represented. Another risk is that one of the assumptions I made when transforming the data might be incorrect, causing the data to now be represented incorrectly. For example, if I labeled a movie as a 'Remake' but the movie has a completely different storyline than the original it should not be considered a remake.  

&emsp; **How was your data sourced/verified for credibility?** This data is sourced from Kaggle.com which is a platform where data scientists and machine learning practitioners can participate in data science competitions, collaborate on projects, share code and datasets, and learn from each other's work. This particular data was originally sourced from movie websites such as IMDB, rotten tomatoes and other movie information sites. These sites are mainly focused on user-driven (viewers and critics) ratings. However, websites such as IMDB are known as the most popular and authoritative source for movie, TV, and celebrity content.

&emsp; **Was your data acquired in an ethical way?** The data on these websites is readily available to the public, and many of them have supporting APIs to assist users in pulling data. Therefore, there is no reason to believe this data was not sourced in an ethical way. 

&emsp; **Are there any legal or regulatory guidelines for your data or project topic?** I have not found any legal or regulatory guidelines regarding the use of film data specifically. However, if any personal identifying information is used, it must be handled in accordance with current data privacy laws and in some cases, consent may be required to use personal data. However, the PII information published on IMBD, Rotten Tomatoes, and the other movie information sites has already been scrutinized based on the current laws and regulations. The main legal guidelines I would need to focus on when using this data is whether I am following the individual website's copyright and creative commons requirements. For example, this data may not be approved for reproduction and sale. 

&emsp; **How would you mitigate any of the ethical implications you have identified?** In order to mitigate any ethical implications when working with this data, it is important that I am aware of any potential biases and that I do not attempt to preserve any existing biases. Transparency is essential, and it is important to take steps to prevent data manipulation or misrepresentation that could lead to misleading conclusions or unfair treatment. I will need to exercise caution and responsibility in the interpretation and reporting of the results to avoid any harm or negative consequences to the individuals and film companies this data is about.

In [20]:
Holywd_gross_df.rename(columns={'Title': 'Film'}, inplace=True)

In [21]:
Holywd_gross_df.dtypes

Film                         object
Year                          int64
Release Date                 object
Genre                        object
Rating                       object
Distributor                  object
Running Time                 object
Movie Info                   object
Budget                       object
Domestic Opening             object
Domestic Sales               object
International Sales (USD)    object
World Wide Sales (USD)       object
dtype: object

# Uncomment below to Save to CSV again...

In [22]:
#Holywd_gross_df.to_csv('Holywd_gross_data.csv', index=False)